Fixed finding the startup lib after install

diff --git a/python-playground b/python-playground
--- a/python-playground
+++ b/python-playground
@@ -1,5 +1,15 @@
 #!/bin/sh
 
-export PYTHONSTARTUP=lib/playground.py
+path="lib/playground.py"
+if [ ! -f $path ]; then
+    path=`python -c 'from distutils.sysconfig import get_python_lib; print get_python_lib()'`"/playground.py"
+    if [ ! -f $path ]; then
+        echo $path
+        echo "Can't find playground.py"
+        exit 1
+    fi
+fi
+
+export PYTHONSTARTUP="$path"
 export PYTHON_SANDBOX_ARGV="$*"
 exec python
